services:
  rag-chatbot-frontend:
    build:
      context: . # Onde o Dockerfile e o código do frontend estão
      dockerfile: Dockerfile         # O nome do Dockerfile dentro do contexto

    container_name: rag_chatbot_frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    networks:
      - chroma-docker_chroma-net
    restart: unless-stopped

networks:
  chroma-docker_chroma-net:
    external: true # Indica que esta rede já existe e não deve ser criada pelo Docker Compose
